name: CI for C++ CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install g++ and make
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make

      # Build the project
      - name: Build
        run: make

      # Run the program with no arguments
      - name: Test run without arguments
        run: ./app

      # Run the program with a test argument
      - name: Test run with argument
        run: ./app TestUser